### ISSUE TITLE
Deprecated REST API is disabled

### ISSUE THREAD

**Issue by gartonb** [mogic-le/youtrack-to-jira#4] opened 2023-06-22 15:29 UTC
{
    "error": "Deprecated REST API is disabled"
    "error_description": "https://blog.jetbrains.com/youtrack/2021/02/discontinuing-the-legacy-rest-api-action-required"
}

**Comment by cweiske** [comment] 2023-06-22 15:38
Duplicate of #3.

**Closed as completed by cweiske** 2023-06-22 15:38 UTC
